blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('comment/<int:pk>/', views.CreateComment.as_view(), name="create_comment"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('<slug:slug>/', views.PostCategoryListView.as_view(), name="post_category_list"),
    path('posts/tags/<str:tag>/', views.PostByTagListView.as_view(), name='post_by_tags'),
    path('', views.PostListView.as_view(), name="post_list"),

]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_medical_diagnostics/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, FeedbackCreateView, FeedbackSuccessView

app_name = MainConfig.name
urlpatterns = [

    path('', home, name='home'),
    path('feedback/', FeedbackCreateView.as_view(), name='feedback'),
    path('feedback_success/', FeedbackSuccessView.as_view(), name='feedback_success'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from . import views

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', views.EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', views.UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', views.EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', views.EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

]

main/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Feedback(models.Model):
    """
    Модель обратной связи
    """
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    email = models.EmailField(max_length=255, verbose_name='Электронный адрес (email)')
    content = models.TextField(verbose_name='Содержимое письма')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'
        ordering = ['-time_create']
        db_table = 'app_feedback'

    def __str__(self):
        return f'Вам письмо от {self.email}'

main/forms.py
from django import forms
from main.models import Feedback


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class FeedbackCreateForm(forms.ModelForm):
    """
    Форма отправки обратной связи
    """

    class Meta:
        model = Feedback
        fields = ('subject', 'email', 'content')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'autocomplete': 'off'})

main/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from blog.models import Post
from .forms import FeedbackCreateForm
from .models import Feedback
from .services.email import send_contact_email_message


def home(request):
    """Вывод основной страницы"""
    extra_context = {
        'post_list': Post.objects.order_by("-view_count")[0:1],
        'post_list_2': Post.objects.order_by("-view_count")[1:3],
        'main_post': Post.objects.order_by('-view_count').first(),
        'main_posts': Post.objects.order_by('-view_count')[1:],
        'other_posts': Post.objects.order_by('-view_count')

    }
    return render(request, 'main/home.html', extra_context)


class FeedbackCreateView(SuccessMessageMixin, CreateView):
    """Реализация заполнения формы фидбека"""
    model = Feedback
    form_class = FeedbackCreateForm
    success_message = 'Ваше письмо успешно отправлено администрации сайта'
    template_name = 'main/email/feedback.html'
    success_url = reverse_lazy('main:feedback_success')

    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save(commit=False)
            send_contact_email_message(feedback.subject, feedback.email, feedback.content, feedback.user_id, )
        return super().form_valid(form)


class FeedbackSuccessView(TemplateView):
    """Реализация успешного заполнения формы фидбека"""
    template_name = 'main/email/feedback_success.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваше письмо отправлено администрации сайта'
        return context

main/templates/main/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script defer src="{% static '/js/jquery-slim.min.js' %}"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <script defer src="{% static '/js/popper.min.js' %}"></script>
    <script defer src="{% static '/js/bootstrap.min.js' %}"></script>
    <script defer src="{% static '/js/holder.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
{% include 'main/header.html' %}
{% block content %}
{% endblock content %}
{# {% include 'main/footer.html' %}#}
</body>
</html>

main/templates/main/footer.html
<footer class="footer">
    {% include 'main/includes/inc_footer.html' %}
</footer>

main/templates/main/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-5 bg-white border-bottom box-shadow">
    {% include 'main/includes/inc_nav_bar.html' %}
</div>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load blog_tags %}
{% load static %}
{% block content %}

<div class="container">
    <div class="col-4 ">
        {% if user.is_authenticated %}
        {% else %}
        <div class="divider"></div>
        <div>Форма подписки</div>
        <a class="text-muted" href="{% url 'users:register' %}">Subscribe</a>
        {% endif %}
    </div>
    <h2 class="w-100 text-dark text-center text-capitalize">Medical blog</h2>

    <hr class="dropdown-divider">
    <div>
        {% include 'main/tag_bar.html' %}
    </div>
    <hr class="dropdown-divider">
    <div class="d-flex justify-content-between align-items-stretch">
        <div class="w-50 flex-fill">
            {% include 'main/includes/card_main_post.html' with post=main_post %}


            <div class="divider"></div>
            {% for m_post in main_posts %}
            {% include 'main/includes/card_other_posts.html' with post=m_post %}
            {% endfor %}
        </div>
        <div class="divider"></div>
        <div class="flex-fill other_news w-25">
            {% for o_post in other_posts %}
            {% include 'main/includes/card_other_posts.html' with post=o_post %}
            {% endfor %}
        </div>
        <div class="divider"></div>
        <div class="flex-fill">
            {% include 'main/sidebar_category.html' %}
        </div>
    </div>
</div>

<style>
    .divider {
        border: 1px solid rgba(0, 0, 0, 0.25);
        margin: 0.25rem;
    }
</style>
{% endblock %}

main/templates/main/sidebar_category.html
{% load blog_tags %}
{% load mptt_tags %}
{% get_list_category as list_category %}
<div class="card">
    <div class="card-header">
        Категории
    </div>
    {% full_tree_for_model blog.Category as categories %}
    <div class="card-body">
         <ul>
            {% recursetree categories %}
                <li>
                 <a href="{% url 'post_category_list' node.slug %}">{{ node.name }}</a>
                </li>

                {% if not node.is_leaf_node %}<ul>{% endif %}
                    {{children}}
                {% if not node.is_leaf_node %}</ul>{% endif %}
            {% endrecursetree %}
        </ul>
      </div>
    </div>

main/templates/main/tag_bar.html
{% load mptt_tags blog_tags %}
<div class="card mb-2">
    <div class="card-header">
        Популярные теги
    </div>
    <div class="card-body">
        <div class="card-text">
            {% popular_tags as tag_list %}
            {% for tag in tag_list %}
            <a href="{% url 'post_by_tags' tag.slug %}">{{ tag.name }} ({{ tag.num_times }})</a>
            {% empty %}
            <a>Популярных тегов не найдено.</a>
            {% endfor %}
        </div>
    </div>
</div>