blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('comment/<int:pk>/', views.CreateComment.as_view(), name="create_comment"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('<slug:slug>/', views.PostCategoryListView.as_view(), name="post_category_list"),
    path('posts/tags/<str:tag>/', views.PostByTagListView.as_view(), name='post_by_tags'),
    path('', views.PostListView.as_view(), name="post_list"),

]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diplom_medical_diagnostics/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, FeedbackCreateView, FeedbackSuccessView

app_name = MainConfig.name
urlpatterns = [

    path('', home, name='home'),
    path('feedback/', FeedbackCreateView.as_view(), name='feedback'),
    path('feedback_success/', FeedbackSuccessView.as_view(), name='feedback_success'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from . import views

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', views.EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', views.UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', views.EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', views.EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

]

main/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Feedback(models.Model):
    """
    Модель обратной связи
    """
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    email = models.EmailField(max_length=255, verbose_name='Электронный адрес (email)')
    content = models.TextField(verbose_name='Содержимое письма')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'
        ordering = ['-time_create']
        db_table = 'app_feedback'

    def __str__(self):
        return f'Вам письмо от {self.email}'

main/forms.py
from django import forms
from main.models import Feedback


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class FeedbackCreateForm(forms.ModelForm):
    """
    Форма отправки обратной связи
    """

    class Meta:
        model = Feedback
        fields = ('subject', 'email', 'content')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'autocomplete': 'off'})

main/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from blog.models import Post
from .forms import FeedbackCreateForm
from .models import Feedback
from .services.email import send_contact_email_message


def home(request):
    """Вывод основной страницы"""
    extra_context = {
        'post_list': Post.objects.order_by("-view_count")[0:1],
        'post_list_2': Post.objects.order_by("-view_count")[1:3],
        'main_post': Post.objects.order_by('-view_count').first(),
        'main_posts': Post.objects.order_by('-view_count')[1:],
        'other_posts': Post.objects.order_by('-view_count')

    }
    return render(request, 'main/home.html', extra_context)


class FeedbackCreateView(SuccessMessageMixin, CreateView):
    """Реализация заполнения формы фидбека"""
    model = Feedback
    form_class = FeedbackCreateForm
    success_message = 'Ваше письмо успешно отправлено администрации сайта'
    template_name = 'main/email/feedback.html'
    success_url = reverse_lazy('main:feedback_success')

    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save(commit=False)
            send_contact_email_message(feedback.subject, feedback.email, feedback.content, feedback.user_id, )
        return super().form_valid(form)


class FeedbackSuccessView(TemplateView):
    """Реализация успешного заполнения формы фидбека"""
    template_name = 'main/email/feedback_success.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваше письмо отправлено администрации сайта'
        return context

main/templates/main/includes/card_main_post.html
{% load mediapath %}
{% load static %}
<div class="d-flex flex-column main__post">
    <h3>{{ post.title }}</h3>
    <div class="d-flex flex-row">
        <img src="{% mediapath post.image %}" alt="Prev" width="200" height="200">
        <p>
            {{ post.text }}
        </p>
    </div>
    <div>
        {{ post.create_at }} / {{ post.view_count }} / {{ post.slug }}
    </div>
</div>

main/templates/main/includes/card_other_posts.html
{% load mediapath %}
{% load static %}
<div class="d-flex flex-column other__post">
    <h3>{{ post.title }}</h3>
    <div class="d-flex flex-row">
        <img src="{% mediapath post.image %}" alt="Prev" width="80" height="80">
        <p>{{ post.text }}</p>
    </div>
    <div>
        {{ post.create_at}} / {{ post.view_count }} / {{ post.slug }}
    </div>
</div>

main/templates/main/includes/inc_footer.html
{% load static %}
<footer class="footer">
    <div class="container-fluid">
        <span class="text-sm-left">&#169; 2023</span>
    </div>
</footer>

main/templates/main/includes/inc_nav_bar.html
{% load static %}

<div class="container">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'main:home' %}">HolaMed</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_list' %}">Posts</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link disabled" href="{% url 'main:feedback' %}">Feedback</a>
                    {% endif %}
                </li>

            </ul>
            <div class="col-4 d-flex justify-content-end align-items-center pr-2">
                {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>